### ISSUE TITLE
Exact Isomorphism bug

### ISSUE THREAD

**Issue by knoxa** [peterrodgers/dover#10]
[isomorphism.zip](https://github.com/peterrodgers/dover/files/933929/isomorphism.zip)

See the target and pattern graphs in the attached zip file: The pattern is 2 nodes connected to each other by 3 edges. The target has two connected nodes of degree 3, but only 2 edges connecting these nodes. The pattern nevertheless gets found in the target.

**Comment by peterrodgers** [comment]
Yep, the subgraph isomporhism algorithm in subgraphIsomorphismFinder() 
assumes a single edge between nodes. This is documented. It can be 
fixed, but there is extra complexity to the algorithm that I did not 
want to deal with.

Peter

**Comment by knoxa** [comment]
Thanks Peter - not a problem as the particular use case I had in mind is better served by increasing the weight on the existing edge between nodes (rather than creating a new edge) in any case. Happy for you to close this issue.

Alan
